token:
  signing:
    key: 412F4428472B4B6250935368566E5970337336763979244226452948404D6789

spring:
  datasource:
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306/RedRolePlay?createDatabaseIfNotExist=true}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

    show-sql: true

    hibernate:
      ddl-auto: update
